# Generated by Django 4.2.6 on 2023-11-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_alter_product_options_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
